###
GET http://localhost:3000/api1/friends

###
GET http://localhost:8080/api1/friends?UserName=myname

###
GET http://localhost:8080/api1/friends/19
###
GET http://localhost:8080/api1/friends/published

###
GET http://localhost:8080/api1/friends?UserID=849f1ae0-f60c-431b-9f01-4b81ea71df4d

###
DELETE  http://localhost:8080/api1/friends
###
DELETE  http://localhost:8080/api1/friends/14

###
POST http://localhost:8080/api1/friends
content-type: application/json
{
    "RequestID": "abc",
    "fromID": "abc" ,
    "toID": "123" 
}



###
PUT http://localhost:8080/api1/friends/1
content-type: application/json
{
    "published": true
}