/**
 * cccc-praying-api
 * The API for CCCC Praying project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse201 { 
    /**
     * Unique ID of the created User.  Exact type/format will depend on your implementation but will likely be either an integer or a string. 
     */
    id?: number | string;
}