/**
 * cccc-praying-api
 * The API for CCCC Praying project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * An object representing information about a Tarpaulin application user. 
 */
export interface LoginInfo { 
    /**
     * Email address for the User.  This is required to be unique among all Users. 
     */
    email?: string;
    /**
     * The User's plain-text password.  This is required when creating a new User and when logging in. 
     */
    password?: string;
}