/**
 * cccc-praying-api
 * The API for CCCC Praying project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * An object representing an error response from the API. 
 */
export interface ModelError { 
    /**
     * A message describing the Error.
     */
    error?: string;
}