/**
 * cccc-praying-api
 * The API for CCCC Praying project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * user infomation include username and church     
 */
export interface UserInfo { 
    /**
     * user's username
     */
    username?: string;
    /**
     * the id of the church that the user joined
     */
    church?: number | string;
}