# coding: utf-8

"""
    cccc-praying-api

    The API for CCCC Praying project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_ofinline_response201_id import OneOfinlineResponse201Id  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfinlineResponse201Id(unittest.TestCase):
    """OneOfinlineResponse201Id unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse201Id(self):
        """Test OneOfinlineResponse201Id"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_ofinline_response201_id.OneOfinlineResponse201Id()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
