# coding: utf-8

"""
    cccc-praying-api

    The API for CCCC Praying project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_user(self):
        """Test case for authenticate_user

        Log in a User.  # noqa: E501
        """
        pass

    def test_get_user_by_id(self):
        """Test case for get_user_by_id

        Fetch data about a specific User.  # noqa: E501
        """
        pass

    def test_new_user(self):
        """Test case for new_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
