# coding: utf-8

"""
    cccc-praying-api

    The API for CCCC Praying project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_user_info_church import OneOfUserInfoChurch  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfUserInfoChurch(unittest.TestCase):
    """OneOfUserInfoChurch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfUserInfoChurch(self):
        """Test OneOfUserInfoChurch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_user_info_church.OneOfUserInfoChurch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
