# coding: utf-8

"""
    cccc-praying-api

    The API for CCCC Praying project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_ofid import OneOfid  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfid(unittest.TestCase):
    """OneOfid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfid(self):
        """Test OneOfid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_ofid.OneOfid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
